insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Karate Kid, Part II, The', 'Action|Adventure|Drama', 'Goldenrod', 'Corny', 'Catharina', '2023-10-24', '2024-04-11');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('To Sir with Love', 'Drama', 'Aquamarine', 'Heriberto', 'Kelly', '2023-11-16', '2023-10-14');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Bringing Up Baby', 'Comedy|Romance', 'Orange', 'Hannie', 'Helsa', '2023-10-31', '2023-09-16');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Gigante', 'Comedy|Drama', 'Indigo', 'Gretna', 'Luisa', '2023-08-01', '2024-02-24');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('All Together', 'Comedy|Drama', 'Violet', 'Giavani', 'Moises', '2023-09-13', '2024-03-28');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Piranha', 'Horror|Sci-Fi', 'Pink', 'Anders', 'Phip', '2023-09-27', '2024-04-25');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Donovan''s Echo', 'Drama|Sci-Fi|Thriller', 'Orange', 'Rufus', 'Saree', '2023-06-26', '2024-04-06');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('El asombroso mundo de Borjamari y Pocholo', '(no genres listed)', 'Red', 'Thatcher', 'Mozes', '2024-01-12', '2023-12-15');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Last Minute, The', 'Drama|Mystery|Thriller', 'Turquoise', 'Gabe', 'Harriot', '2023-06-04', '2024-01-17');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Morning for the Osone Family', '(no genres listed)', 'Green', 'Hurleigh', 'Symon', '2023-10-01', '2023-07-23');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Playing', 'Documentary', 'Pink', 'Myron', 'Candie', '2023-05-06', '2024-01-02');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Band''s Visit, The (Bikur Ha-Tizmoret)', 'Comedy|Drama', 'Teal', 'Norry', 'Colin', '2023-07-30', '2023-11-07');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Psycho Beach Party', 'Comedy|Horror|Thriller', 'Orange', 'Delinda', 'Bev', '2023-04-26', '2023-09-25');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Reconstituirea (Reconstruction)', 'Comedy|Drama', 'Yellow', 'Alfonso', 'Jessie', '2024-04-09', '2024-04-21');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Titfield Thunderbolt, The', 'Comedy', 'Crimson', 'Elysee', 'Vilhelmina', '2023-09-05', '2023-11-11');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Caótica Ana', 'Comedy|Drama|Mystery|Romance', 'Puce', 'Grady', 'Darby', '2023-08-11', '2023-08-04');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Real Blonde, The', 'Comedy', 'Blue', 'Deny', 'Worthy', '2023-06-30', '2023-06-29');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Soft Shell Man (Un crabe dans la tête)', 'Drama|Romance', 'Yellow', 'Hermie', 'Townie', '2023-06-26', '2023-06-02');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Love Comes Softly', 'Drama|Romance|Western', 'Teal', 'Ingar', 'Peirce', '2024-03-17', '2024-01-08');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Dear White People', 'Comedy|Drama', 'Goldenrod', 'Kenneth', 'Renaud', '2023-08-14', '2023-06-11');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Popcorn', 'Horror', 'Crimson', 'Lewie', 'Madelaine', '2024-04-08', '2023-10-06');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Daltry Calhoun', 'Comedy|Drama', 'Red', 'Hector', 'Mada', '2024-03-05', '2023-12-12');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Andy Hardy''s Blonde Trouble', 'Comedy|Romance', 'Purple', 'Mathew', 'Neil', '2024-04-03', '2023-09-18');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Pete Smalls Is Dead', 'Comedy', 'Pink', 'Chrisy', 'Gawain', '2023-10-05', '2023-11-17');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('After the Life', 'Crime|Drama', 'Yellow', 'Cynthia', 'Cathee', '2023-05-15', '2023-10-21');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Bonaerense, El', 'Action|Drama', 'Teal', 'Mayor', 'Cello', '2023-11-19', '2024-03-07');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Now and Forever', 'Drama|Romance', 'Mauv', 'Lowrance', 'Boris', '2023-11-09', '2023-10-26');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('It Happened Tomorrow', 'Comedy|Fantasy', 'Pink', 'Eldin', 'Matthaeus', '2024-04-16', '2023-07-08');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Come and See (Idi i smotri)', 'Drama|War', 'Aquamarine', 'Innis', 'Morie', '2024-01-13', '2023-04-28');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('City Slacker', 'Romance', 'Khaki', 'Harold', 'Dennie', '2023-09-12', '2023-08-08');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('City of Fear', 'Crime|Thriller', 'Green', 'Alisun', 'Conrade', '2024-03-26', '2024-03-20');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Pokémon 3: The Movie', 'Animation|Children', 'Teal', 'Dyane', 'Shae', '2023-12-18', '2023-12-07');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Vessel of Wrath', 'Drama', 'Orange', 'Rana', 'Jeffie', '2024-03-14', '2023-10-29');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Chasing Ice', 'Documentary', 'Crimson', 'Nehemiah', 'Linus', '2023-07-25', '2023-12-07');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Bill Burr: I''m Sorry You Feel That Way', 'Comedy', 'Fuscia', 'Pearce', 'Dill', '2023-10-19', '2023-11-02');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Colors of the Mountain, The (Los colores de la montaña)', 'Drama', 'Fuscia', 'Jaquenette', 'Dillon', '2023-12-25', '2023-12-12');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Sophie''s Revenge (Fei chang wan mei)', 'Comedy|Romance', 'Purple', 'Kellby', 'Sibeal', '2023-10-20', '2023-08-06');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('King of Germany', 'Comedy', 'Pink', 'Dugald', 'Dwight', '2023-12-18', '2023-08-20');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Heroic Cops (Jing wang shuang xiong)', 'Action|Crime', 'Crimson', 'Auroora', 'Dimitry', '2023-09-07', '2023-09-30');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Cameraman, The', 'Comedy|Drama|Romance', 'Blue', 'Melina', 'Rodolfo', '2023-09-20', '2024-03-13');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Ishq', 'Action|Comedy|Drama|Musical|Romance', 'Violet', 'Odele', 'Loni', '2023-08-05', '2024-02-10');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Temple Grandin', 'Drama', 'Fuscia', 'Sydelle', 'Verene', '2023-10-24', '2023-11-11');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Scenic Route, The', 'Drama', 'Purple', 'Massimiliano', 'Alan', '2023-06-22', '2023-10-15');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Flesh Gordon', 'Adventure|Comedy|Sci-Fi', 'Blue', 'Nara', 'Waring', '2023-07-08', '2023-10-06');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Burning Plain, The', 'Drama|Romance', 'Turquoise', 'Rouvin', 'Emmeline', '2024-03-21', '2024-04-01');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Only Old Men Are Going to Battle (V boy idut odni stariki)', 'Comedy|Drama|War', 'Indigo', 'Ferrell', 'Andonis', '2023-06-13', '2023-09-09');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Unknown Soldier, The (Unbekannte Soldat, Der)', 'Documentary', 'Maroon', 'Fern', 'Thorin', '2024-02-22', '2023-10-16');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Left-Hand Side of the Fridge, The (Moitié gauche du frigo, La)', 'Comedy', 'Fuscia', 'Phillip', 'Ethelred', '2024-04-05', '2023-06-05');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Kansas', 'Crime|Drama', 'Turquoise', 'Clarine', 'Demetris', '2023-08-16', '2023-12-07');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Outsider', 'Drama', 'Mauv', 'Lark', 'Paddy', '2023-10-23', '2023-12-14');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Black Legion', 'Crime|Drama', 'Indigo', 'Moselle', 'Michaela', '2024-01-12', '2024-03-07');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Great Day in the Morning', 'Western', 'Orange', 'Katine', 'Cyb', '2024-01-27', '2023-11-23');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Walk on the Moon, A', 'Drama|Romance', 'Maroon', 'Tildi', 'Mikey', '2024-04-07', '2024-04-17');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Stripes', 'Comedy|War', 'Mauv', 'Steven', 'Wynn', '2024-02-11', '2024-01-31');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Slingshot Hip Hop', '(no genres listed)', 'Orange', 'Karyl', 'Alfred', '2023-09-13', '2023-05-21');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Enfer, L''', 'Drama', 'Purple', 'Lori', 'Charmain', '2023-10-12', '2024-03-05');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Wilder Napalm', 'Comedy|Fantasy|Romance', 'Turquoise', 'Ward', 'Don', '2024-04-22', '2023-08-17');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Goal! The Dream Begins (Goal!)', 'Drama', 'Violet', 'Joe', 'Korrie', '2023-06-21', '2023-12-23');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Last Man, The', 'Comedy|Romance|Sci-Fi', 'Blue', 'Zaccaria', 'Christabel', '2023-07-03', '2024-04-07');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Curtis''s Charm', 'Comedy|Drama', 'Crimson', 'Kiele', 'Marice', '2023-08-19', '2024-01-22');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Beloved/Friend (a.k.a. Amigo/Amado) (Amic/Amat)', 'Drama', 'Maroon', 'Rip', 'Charlene', '2023-12-22', '2023-06-08');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Madhouse', 'Comedy', 'Fuscia', 'Bear', 'Joy', '2023-11-14', '2024-01-03');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Chocchan''s Story (Chocchan monogatari)', 'Animation|Drama|War', 'Pink', 'My', 'Danit', '2024-04-13', '2024-01-23');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Luna, La', 'Drama', 'Blue', 'Grover', 'Chloe', '2023-12-01', '2023-07-07');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Daisy Miller', 'Drama', 'Turquoise', 'Kara-lynn', 'Marie', '2024-03-14', '2023-10-04');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Buffy the Vampire Slayer', 'Action|Comedy|Horror', 'Teal', 'Timothea', 'Jonie', '2023-09-06', '2023-08-20');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Tulpan', 'Comedy|Drama', 'Indigo', 'Amata', 'Gaylor', '2024-04-18', '2023-09-19');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Dream (Bi-mong)', 'Drama|Fantasy|Mystery|Romance', 'Khaki', 'Elene', 'Zilvia', '2023-08-18', '2023-07-16');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Dangerous Lives of Altar Boys, The', 'Drama', 'Green', 'Fidela', 'Marris', '2023-12-17', '2024-02-05');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Post Grad', 'Comedy', 'Pink', 'Moreen', 'Imojean', '2023-10-19', '2024-01-30');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('She Wore a Yellow Ribbon', 'Western', 'Blue', 'Francesca', 'Leanna', '2024-02-21', '2023-08-27');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Last Man on Earth, The (Ultimo uomo della Terra, L'')', 'Drama|Horror|Sci-Fi', 'Purple', 'Iain', 'Bartram', '2023-11-03', '2023-09-26');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Moscow Does Not Believe in Tears (Moskva slezam ne verit)', 'Drama|Romance', 'Turquoise', 'Lyle', 'Duffy', '2023-12-29', '2023-07-15');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Black and White', 'Drama', 'Crimson', 'Kennedy', 'Anthea', '2023-05-21', '2023-10-15');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Nutty Professor, The', 'Comedy|Fantasy|Romance|Sci-Fi', 'Mauv', 'Wilmette', 'Philipa', '2023-11-23', '2023-06-02');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Birder''s Guide to Everything, A', 'Comedy', 'Indigo', 'Josefina', 'Durant', '2023-06-13', '2023-07-20');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Men with Guns', 'Action|Drama', 'Mauv', 'Dorolice', 'Wendel', '2023-05-08', '2024-03-30');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Rendezvous in Paris (Rendez-vous de Paris, Les)', 'Comedy|Romance', 'Puce', 'Alys', 'Pam', '2024-03-03', '2023-08-11');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Brothers Karamazov, The', 'Drama', 'Maroon', 'Henrietta', 'Ange', '2023-10-04', '2023-05-30');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Way Back, The', 'Drama', 'Khaki', 'Vergil', 'Seumas', '2023-05-13', '2023-11-10');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Ready to Rumble', 'Comedy', 'Orange', 'Raimundo', 'Estele', '2023-12-07', '2024-02-03');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Second Woman, The', 'Drama|Film-Noir|Mystery', 'Puce', 'Hedvig', 'Chelsey', '2024-04-23', '2024-01-27');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Two Jakes, The', 'Drama', 'Khaki', 'Lavena', 'Hana', '2023-08-31', '2023-08-27');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Gertie the Dinosaur', 'Animation|Children|Comedy', 'Fuscia', 'Mariann', 'Merill', '2023-09-19', '2023-08-11');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Saving Shiloh', 'Children|Drama', 'Puce', 'Averill', 'Auroora', '2023-06-24', '2024-04-09');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Funeral, The (Ososhiki)', 'Comedy', 'Yellow', 'Cathyleen', 'Kliment', '2023-08-19', '2023-07-15');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Grave of the Fireflies (Hotaru no haka)', 'Animation|Drama|War', 'Yellow', 'Pascal', 'Farrel', '2024-04-12', '2023-12-18');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Out 1: Spectre', 'Comedy|Drama|Thriller', 'Violet', 'Anastassia', 'Roberto', '2024-02-10', '2023-07-14');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Dead Leaves', 'Action|Adventure|Animation|Comedy|Sci-Fi', 'Aquamarine', 'Kevina', 'Drucie', '2024-03-24', '2024-01-14');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('50 Children: The Rescue Mission of Mr. And Mrs. Kraus', 'Documentary', 'Mauv', 'Roosevelt', 'Anatollo', '2023-09-16', '2023-10-26');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Looking for Richard', 'Documentary|Drama', 'Aquamarine', 'Maisey', 'Steve', '2024-02-07', '2023-11-12');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('She Wouldn''t Say Yes', 'Comedy|Romance', 'Pink', 'Beau', 'Kassia', '2023-10-11', '2023-09-10');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Surviving Christmas', 'Comedy', 'Mauv', 'Erhard', 'Olav', '2024-02-20', '2023-08-25');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Child Bride', 'Drama', 'Teal', 'Ethyl', 'Maryrose', '2023-09-30', '2023-10-16');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Who Am I? (Wo shi shei)', 'Action|Adventure|Comedy|Sci-Fi|Thriller', 'Violet', 'Gizela', 'Leontyne', '2024-01-13', '2023-05-12');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Victor Sjöström: Ett porträtt', 'Documentary', 'Blue', 'Janetta', 'Crichton', '2024-01-19', '2023-08-16');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Total Recall', 'Action|Adventure|Sci-Fi|Thriller', 'Violet', 'Noellyn', 'Ev', '2023-10-10', '2023-09-13');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Avenging Angelo', 'Action|Comedy|Crime', 'Blue', 'Nestor', 'Tommy', '2023-06-02', '2023-08-04');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Lusty Men, The', 'Action|Drama|Western', 'Blue', 'Tabatha', 'Ferrell', '2023-07-24', '2023-06-29');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Young Lions, The', 'Drama|War', 'Blue', 'Ellen', 'Kellie', '2024-02-16', '2024-01-29');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Back to the Secret Garden', 'Adventure|Children|Fantasy', 'Purple', 'Morgun', 'Noelani', '2023-11-20', '2023-12-11');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('I''m Not Scared (Io non ho paura)', 'Drama|Mystery|Thriller', 'Turquoise', 'Eddy', 'Wendel', '2023-12-11', '2023-07-01');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Submerged', 'Action', 'Pink', 'Aldridge', 'Saba', '2023-08-14', '2023-11-18');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('The Amazing Screw-On Head', 'Action|Adventure|Animation|Comedy|Sci-Fi', 'Teal', 'Shepperd', 'Crichton', '2024-04-05', '2024-01-25');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Kiss Kiss Bang Bang', 'Comedy|Crime|Mystery|Thriller', 'Pink', 'Caren', 'Melodie', '2023-08-03', '2023-12-03');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('To Sleep with Anger', 'Drama', 'Goldenrod', 'Inigo', 'Fair', '2024-04-12', '2023-12-27');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Love Is All You Need (Den skaldede frisør)', 'Comedy|Drama|Romance', 'Green', 'Mordy', 'Aloin', '2024-04-06', '2023-09-23');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Undercurrent', 'Film-Noir|Thriller', 'Puce', 'Yelena', 'Bari', '2024-03-29', '2024-04-10');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Belle and Sebastien (Belle et Sébastien)', 'Adventure', 'Pink', 'Bone', 'Cindy', '2024-04-01', '2024-03-17');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Me and You and Everyone We Know', 'Comedy|Drama', 'Purple', 'Wiley', 'Brynne', '2023-08-30', '2023-06-05');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Glimpse Inside the Mind of Charles Swan III, A', 'Comedy', 'Khaki', 'Don', 'Celestina', '2024-03-14', '2023-10-09');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Mumford', 'Comedy|Drama', 'Goldenrod', 'Barry', 'Alfy', '2024-02-17', '2023-07-30');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Taking of Pelham 1 2 3, The', 'Crime|Drama|Thriller', 'Teal', 'Bil', 'Mathilda', '2023-09-29', '2024-02-27');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Blinkity Blank', 'Animation', 'Pink', 'Lammond', 'Leicester', '2023-10-08', '2023-10-10');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Everest', 'Documentary|IMAX', 'Pink', 'Robbie', 'Delcina', '2023-05-03', '2023-05-18');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Life Is What You Make It (Linha de Passe)', 'Drama', 'Aquamarine', 'Annmarie', 'Sinclare', '2023-09-28', '2023-07-16');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Bombay Talkie', 'Drama|Musical|Romance', 'Turquoise', 'Laurette', 'Ede', '2023-06-17', '2024-02-09');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Beauty and the Beast (La belle et la bête)', 'Drama|Fantasy', 'Red', 'Carroll', 'Clary', '2024-03-16', '2024-02-28');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Green Room, The (a.k.a. Vanishing Fiancee) (La chambre verte)', 'Drama', 'Aquamarine', 'Morey', 'Hugo', '2023-07-04', '2023-10-16');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Simon Magus', 'Drama|Fantasy|Mystery|Romance', 'Goldenrod', 'Blondell', 'Aubert', '2023-12-24', '2023-12-12');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Métamorphose des cloportes, La', 'Comedy|Crime', 'Puce', 'Monique', 'Lorenzo', '2023-08-15', '2023-09-24');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Twilight Saga: New Moon, The', 'Drama|Fantasy|Horror|Romance|Thriller', 'Goldenrod', 'Elisha', 'Mason', '2023-05-20', '2023-10-20');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Judge Dredd', 'Action|Crime|Sci-Fi', 'Mauv', 'Derick', 'Marshal', '2023-05-17', '2024-02-20');

-- 댓글

insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (1, 'Eastern cottontail rabbit', 'Sanford', 'Abbe', '2023-07-03', '2023-05-28');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (2, 'Heron, boat-billed', 'Adolpho', 'Moina', '2024-04-15', '2023-08-07');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (3, 'American alligator', 'Jaye', 'Emmett', '2024-03-30', '2023-08-26');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (4, 'Seal, southern elephant', 'Noak', 'Tony', '2023-10-31', '2024-02-08');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (5, 'Lemur, ring-tailed', 'Imelda', 'Dulcea', '2024-01-27', '2024-02-21');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (6, 'Ocelot', 'Cherrita', 'Torrey', '2023-10-26', '2023-05-13');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (7, 'Corella, long-billed', 'Ive', 'Marlo', '2024-03-23', '2023-05-29');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (8, 'Black-backed magpie', 'Kali', 'Angelica', '2024-04-21', '2023-05-28');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (9, 'Red-breasted cockatoo', 'Merola', 'Gabrila', '2023-07-30', '2023-10-19');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (10, 'Common nighthawk', 'Ernest', 'Gillian', '2023-09-30', '2024-01-21');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (11, 'Steenbuck', 'Carena', 'Tammie', '2023-05-28', '2023-11-12');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (12, 'Wood pigeon', 'Roxanne', 'Eydie', '2023-08-24', '2024-03-25');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (13, 'Two-toed sloth', 'Reba', 'Padget', '2023-08-29', '2024-03-13');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (14, 'Carpet snake', 'Blanche', 'Rancell', '2024-04-19', '2024-03-04');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (15, 'Tiger snake', 'Oberon', 'Alonzo', '2023-11-03', '2024-04-12');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (16, 'White-winged black tern', 'Catie', 'Jed', '2024-04-09', '2024-02-10');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (17, 'Wallaby, tammar', 'Ethyl', 'Claudelle', '2023-10-10', '2023-05-24');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (18, 'Long-tailed skua', 'Mortie', 'Hayley', '2023-11-24', '2023-06-29');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (19, 'Pigeon, wood', 'Trudey', 'Winfred', '2024-03-12', '2023-09-14');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (20, 'Pied cormorant', 'Bartram', 'Janifer', '2023-11-28', '2023-09-24');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (21, 'African porcupine', 'Gwendolyn', 'Jania', '2023-12-09', '2024-04-18');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (22, 'Green heron', 'Adriena', 'Rodi', '2023-09-16', '2023-08-03');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (23, 'Admiral, indian red', 'Kanya', 'Edgardo', '2023-05-16', '2023-11-01');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (24, 'Baboon, olive', 'Andras', 'Guido', '2023-09-06', '2023-10-20');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (25, 'Osprey', 'Allister', 'Cosetta', '2024-03-02', '2024-02-03');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (26, 'Southern hairy-nosed wombat', 'Noelyn', 'Geneva', '2024-02-13', '2024-02-06');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (27, 'Glider, feathertail', 'Kitty', 'Jamima', '2023-12-22', '2023-11-11');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (28, 'Hoary marmot', 'Ivar', 'Spense', '2024-03-31', '2023-10-14');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (29, 'Canadian tiger swallowtail butterfly', 'Jesselyn', 'Carlee', '2024-02-14', '2023-06-01');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (30, 'Small Indian mongoose', 'Kinny', 'Merilee', '2024-01-22', '2023-06-25');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (31, 'Ferruginous hawk', 'Noreen', 'Mellie', '2023-10-02', '2023-08-02');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (32, 'Blue crane', 'Adelbert', 'Cathy', '2024-03-14', '2023-12-05');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (33, 'Mongoose, small indian', 'Mayor', 'Ansley', '2023-10-26', '2023-05-25');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (34, 'Crane, blue', 'Hurley', 'Iolande', '2023-12-25', '2023-06-21');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (35, 'Sable antelope', 'Noel', 'Almire', '2023-10-02', '2023-09-19');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (36, 'Red-billed hornbill', 'Locke', 'Haroun', '2023-09-08', '2023-09-21');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (37, 'Common wolf', 'Yule', 'Melanie', '2024-03-31', '2024-04-14');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (38, 'Desert spiny lizard', 'Kerrin', 'Garald', '2023-05-26', '2023-08-25');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (39, 'Kingfisher, white-throated', 'Kaitlynn', 'Jolyn', '2023-12-26', '2024-02-17');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (40, 'Tree porcupine', 'Asher', 'Hermie', '2023-11-22', '2023-09-20');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (41, 'Sockeye salmon', 'Damian', 'Nonna', '2023-08-15', '2023-10-24');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (42, 'Dolphin, striped', 'Aluino', 'Keven', '2024-01-04', '2024-04-14');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (43, 'Goldeneye, barrows', 'Karleen', 'Katharina', '2024-04-09', '2024-02-18');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (44, 'Legaan, water', 'Dugald', 'Leoine', '2023-05-05', '2024-04-16');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (45, 'Devil, tasmanian', 'Mason', 'Aubree', '2023-08-31', '2024-02-23');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (46, 'Bandicoot, short-nosed', 'Ced', 'Tanhya', '2023-12-01', '2023-10-03');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (47, 'Wallaby, agile', 'Alikee', 'Fernando', '2023-08-20', '2024-03-04');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (48, 'Ring-tailed possum', 'Rolando', 'Jayne', '2023-11-25', '2024-02-13');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (49, 'Hyena, striped', 'Roldan', 'Creigh', '2023-11-19', '2023-11-11');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (50, 'Baboon, yellow', 'Julietta', 'Cristina', '2023-08-22', '2023-11-05');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (51, 'Southern lapwing', 'Adrian', 'Connor', '2023-06-26', '2023-10-01');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (52, 'Wolf spider', 'Dyann', 'Aloysius', '2024-02-15', '2023-12-04');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (53, 'Snake, eastern indigo', 'Pat', 'Fayina', '2023-11-17', '2024-01-03');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (54, 'Goose, knob-nosed', 'Geneva', 'Vyky', '2023-10-29', '2023-10-02');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (55, 'Pheasant, common', 'Josepha', 'Pierce', '2023-06-25', '2023-05-06');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (56, 'Black-eyed bulbul', 'Audry', 'Basil', '2023-09-14', '2023-11-23');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (57, 'Monkey, black spider', 'Pauli', 'Deerdre', '2024-02-24', '2023-05-17');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (58, 'Bengal vulture', 'Anneliese', 'Kris', '2024-02-26', '2023-12-01');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (59, 'Cormorant, king', 'Robena', 'Dale', '2023-11-28', '2024-03-05');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (60, 'Wallaroo, common', 'Judas', 'Corena', '2023-05-29', '2023-08-14');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (61, 'Little cormorant', 'Norton', 'Gearard', '2023-12-24', '2024-04-18');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (62, 'Jackal, indian', 'Selia', 'Maiga', '2023-08-17', '2024-04-08');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (63, 'Coatimundi, white-nosed', 'Joe', 'Stirling', '2023-08-14', '2023-09-20');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (64, 'Golden brush-tailed possum', 'Annnora', 'Selestina', '2024-01-06', '2023-07-06');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (65, 'Bee-eater (unidentified)', 'Jobey', 'Emylee', '2024-03-08', '2024-03-25');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (66, 'Magellanic penguin', 'Katrinka', 'Emmeline', '2023-12-28', '2024-04-06');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (67, 'Plains zebra', 'Rozalin', 'Cathlene', '2024-02-01', '2023-05-10');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (68, 'Common langur', 'Norrie', 'Charil', '2024-01-05', '2023-07-07');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (69, 'Golden-mantled ground squirrel', 'Godwin', 'Ferdie', '2023-05-10', '2023-05-13');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (70, 'Pelican, eastern white', 'Jemmie', 'Lorry', '2024-04-22', '2023-09-16');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (71, 'Cuis', 'Chaim', 'Sheffie', '2024-02-08', '2023-06-15');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (72, 'Fringe-eared oryx', 'Rafaela', 'Antonella', '2024-02-24', '2023-06-23');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (73, 'Skunk, striped', 'Cayla', 'Shellysheldon', '2023-12-24', '2024-01-21');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (74, 'Ring-tailed lemur', 'Dorene', 'Theadora', '2023-11-28', '2023-11-09');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (75, 'Andean goose', 'Ermanno', 'Elston', '2024-01-29', '2023-09-09');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (76, 'Nelson ground squirrel', 'Tracie', 'Bryant', '2023-06-06', '2023-08-10');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (77, 'Owl, great horned', 'Valeda', 'Bessie', '2023-10-24', '2023-07-20');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (78, 'Egyptian viper', 'Roanna', 'Courtnay', '2023-09-09', '2024-04-15');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (79, 'Heron, boat-billed', 'Andeee', 'Stephi', '2023-07-15', '2024-02-26');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (80, 'Heron, striated', 'Kincaid', 'Vachel', '2023-06-15', '2023-10-25');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (81, 'Honey badger', 'Maudie', 'Alley', '2023-12-10', '2023-12-12');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (82, 'Campo flicker', 'Valaree', 'Nikki', '2024-03-19', '2024-02-12');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (83, 'Legaan, water', 'Emma', 'Dana', '2024-01-14', '2023-05-28');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (84, 'Hawk, red-tailed', 'Kendal', 'Chas', '2023-09-05', '2023-11-07');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (85, 'Crane, wattled', 'Conny', 'Kimberlyn', '2023-06-12', '2023-11-16');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (86, 'Crane, black-crowned', 'Angelica', 'Bobina', '2023-06-28', '2023-12-17');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (87, 'Rattlesnake, eastern diamondback', 'Fletcher', 'Fallon', '2023-12-03', '2023-10-10');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (88, 'Booby, masked', 'Karry', 'Deane', '2023-06-24', '2023-07-12');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (89, 'Greater rhea', 'Peri', 'Jared', '2024-02-21', '2023-07-08');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (90, 'Bushpig', 'Vale', 'Mollie', '2023-05-19', '2024-03-05');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (91, 'Sheep, stone', 'Erek', 'Jud', '2023-06-13', '2023-12-19');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (92, 'Oriental white-backed vulture', 'Allissa', 'Ryley', '2023-12-25', '2023-07-05');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (93, 'Porcupine, north american', 'Jocelin', 'Jemima', '2023-05-09', '2023-10-07');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (94, 'Topi', 'Levin', 'Herta', '2024-04-19', '2023-12-22');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (95, 'Camel, dromedary', 'Valli', 'Gibbie', '2024-01-12', '2023-05-02');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (96, 'Boa, mexican', 'Keane', 'Northrop', '2023-12-13', '2024-02-09');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (97, 'Savanna fox', 'Corly', 'Libbey', '2023-10-03', '2023-12-16');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (98, 'Tortoise, asian foreset', 'Cordelia', 'Donall', '2023-11-16', '2023-11-20');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (99, 'Moose', 'Lorry', 'Norine', '2023-10-27', '2024-04-06');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (100, 'Short-beaked echidna', 'Avril', 'Sacha', '2024-04-04', '2024-01-24');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (101, 'Heron, little', 'Timoteo', 'Chucho', '2023-06-07', '2023-10-06');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (102, 'Tropical buckeye butterfly', 'Barrett', 'Leonard', '2023-09-12', '2023-12-23');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (103, 'Fork-tailed drongo', 'Susana', 'Linoel', '2023-12-16', '2023-06-28');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (104, 'California sea lion', 'Barrie', 'Cully', '2023-07-27', '2023-10-21');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (105, 'Dragon, ornate rock', 'Glenn', 'Etheline', '2023-12-20', '2023-10-26');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (106, 'Caracal', 'Eugine', 'Chip', '2024-04-23', '2024-02-05');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (107, 'Stick insect', 'Tomas', 'Petronella', '2024-03-27', '2024-02-26');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (108, 'Brocket, red', 'Pinchas', 'Trenton', '2024-03-16', '2023-09-01');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (109, 'Oriental short-clawed otter', 'Lane', 'Candis', '2023-11-03', '2023-10-02');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (110, 'Weaver, sociable', 'Linda', 'Leeann', '2024-02-04', '2023-12-16');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (111, 'Hornbill, yellow-billed', 'Carter', 'Margareta', '2024-01-05', '2023-11-10');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (112, 'Bee-eater (unidentified)', 'Ethelind', 'Kile', '2024-02-09', '2024-03-18');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (113, 'African snake (unidentified)', 'Waly', 'Jonathan', '2024-02-13', '2023-11-10');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (114, 'Dragon, frilled', 'Joyce', 'Sherill', '2023-08-05', '2023-09-03');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (115, 'Bettong, brush-tailed', 'Carmine', 'Kathryn', '2024-01-14', '2024-04-16');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (116, 'Trumpeter, dark-winged', 'Izabel', 'Maia', '2023-10-08', '2023-12-31');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (117, 'Lion, south american sea', 'Jerry', 'Sybil', '2023-08-16', '2023-12-15');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (118, 'Kingfisher, pied', 'Eadie', 'Brenna', '2023-06-13', '2023-09-14');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (119, 'Boa, cook''s tree', 'Abbi', 'Erhart', '2023-05-29', '2024-03-26');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (120, 'Japanese macaque', 'Marten', 'Guido', '2023-10-04', '2023-10-08');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (121, 'Four-spotted skimmer', 'Scotty', 'Hector', '2023-05-10', '2023-11-25');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (122, 'Glossy ibis', 'Jaymee', 'Bram', '2023-05-20', '2023-06-02');
insert into article_comment (article_id, content, created_by, modified_by, created_at, modified_at) values (123, 'Bulbul, african red-eyed', 'Rockie', 'Mikael', '2023-12-02', '2024-02-09');
